// Fill out your copyright notice in the Description page of Project Settings.


#include "UI/Panel/MaterialGeneratePanel.h"

#include "Blueprint/WidgetTree.h"
#include "Components/Border.h"
#include "Components/Button.h"
#include "Components/CanvasPanel.h"
#include "Components/CanvasPanelSlot.h"
#include "Components/TextBlock.h"
#include "Components/TileView.h"
#include "Components/VerticalBox.h"
#include "Components/VerticalBoxSlot.h"
#include "Data/MaterialThumbnailData.h"
#include "UI/Widget/ListingMaterials.h"

class UCanvasPanelSlot;
class UVerticalBoxSlot;
class UButton;
class UTextBlock;

bool UMaterialGeneratePanel::Initialize()
{
	// 1. ë¶€ëª¨ ì´ˆê¸°í™”
	bool bSuccess = Super::Initialize();
	if (!bSuccess) return false;

	// 2. ì¶”ê°€ ì´ˆê¸°í™”
	CreateMaterialTypeEnumBtns();

	MatTypeBtnArray[0]->OnClicked.AddDynamic(this,&UMaterialGeneratePanel::OnTireBtnClicked);
	MatTypeBtnArray[1]->OnClicked.AddDynamic(this,&UMaterialGeneratePanel::OnFoliageBtnClicked);
	MatTypeBtnArray[2]->OnClicked.AddDynamic(this,&UMaterialGeneratePanel::OnVideoBtnClicked);
	MatTypeBtnArray[3]->OnClicked.AddDynamic(this,&UMaterialGeneratePanel::OnSubsurfaceBtnClicked);
	MatTypeBtnArray[4]->OnClicked.AddDynamic(this,&UMaterialGeneratePanel::OnCarPaintBtnClicked);
	MatTypeBtnArray[5]->OnClicked.AddDynamic(this,&UMaterialGeneratePanel::OnWaterBtnClicked);
	MatTypeBtnArray[6]->OnClicked.AddDynamic(this,&UMaterialGeneratePanel::OnEmissiveBtnClicked);
	MatTypeBtnArray[7]->OnClicked.AddDynamic(this,&UMaterialGeneratePanel::OnFabricBtnClicked);
	MatTypeBtnArray[8]->OnClicked.AddDynamic(this,&UMaterialGeneratePanel::OnGlassBtnClicked);
	MatTypeBtnArray[9]->OnClicked.AddDynamic(this,&UMaterialGeneratePanel::OnStandardBtnClicked);

	MaterialCreateBtn->OnClicked.AddDynamic(this, &UMaterialGeneratePanel::OnCreateMaterialBtnClicked);
	
	
	// 3. ì„±ê³µ ë°˜í™˜
	return true;
}

void UMaterialGeneratePanel::NativeConstruct()
{
	Super::NativeConstruct();

	MaterialTypeChangePanelOnOffBtn->OnClicked.AddDynamic(this, &UMaterialGeneratePanel::TurnOnOffMaterialTypeChangePanel);
}

void UMaterialGeneratePanel::TurnOnOffMaterialTypeChangePanel()
{
	if (MaterialTypeChangePanel->GetVisibility() == ESlateVisibility::Visible)
	{
		MaterialTypeChangePanel->SetVisibility(ESlateVisibility::Hidden);
	}
	else
	{
		MaterialTypeChangePanel->SetVisibility(ESlateVisibility::Visible);
	}
}


void UMaterialGeneratePanel::CreateMaterialTypeEnumBtns()
{

	MatEnumPtr = StaticEnum<EMaterialType>();


	// 1ï¸âƒ£ Border ìƒì„±
	MaterialTypeChangePanel = WidgetTree->ConstructWidget<UBorder>(UBorder::StaticClass());
	MaterialTypeChangePanel->SetBrushColor(FLinearColor::Black); // ê²€ì€ìƒ‰ ë°°ê²½
	MaterialTypeChangePanel->SetPadding(FMargin(5.f)); // ë²„íŠ¼ê³¼ ì—¬ë°±

	// 2ï¸âƒ£ VerticalBox ìƒì„±
	UVerticalBox* ButtonBox = WidgetTree->ConstructWidget<UVerticalBox>(UVerticalBox::StaticClass());

	// 3ï¸âƒ£ Border ì•ˆì— VerticalBox ì¶”ê°€
	MaterialTypeChangePanel->AddChild(ButtonBox);

	// 4ï¸âƒ£ Canvasì— Border ì¶”ê°€
	UCanvasPanelSlot* CanvasSlot = MaterialsLeftPanel->AddChildToCanvas(MaterialTypeChangePanel);
	CanvasSlot->SetAutoSize(true);
	CanvasSlot->SetPosition(FVector2D(18, -480));

	// ğŸ”¹ 3ï¸âƒ£ Enum ê°’ë§Œí¼ ë²„íŠ¼ ìƒì„±
	for (int32 i = 0; i < MatEnumPtr->NumEnums() - 1; ++i)
	{
		UButton* Button = WidgetTree->ConstructWidget<UButton>(UButton::StaticClass());

		//ìƒì„±ëœ ë²„íŠ¼ë“¤ì„ Arrayì— ë‹´ê¸°. ë°”ê¹¥ì—ì„œ ì¸ë±ìŠ¤ í•˜ë‚˜í•˜ë‚˜ì— ì ‘ê·¼í•´ì„œ ì´ë²¤íŠ¸ë¥¼ ìˆ˜ë™ìœ¼ë¡œ ê±¸ì–´ì£¼ê¸° ìœ„í•´.
		MatTypeBtnArray.Add(Button);
		UTextBlock* Text = WidgetTree->ConstructWidget<UTextBlock>(UTextBlock::StaticClass());
		
		FText EnumName = MatEnumPtr->GetDisplayNameTextByIndex(i);
		Text->SetText(EnumName);
		Button->AddChild(Text);

		UVerticalBoxSlot* BoxSlot = ButtonBox->AddChildToVerticalBox(Button);
		BoxSlot->SetPadding(FMargin(3.f));
		
		// ğŸ”¹ ìŠ¤íƒ€ì¼ ì„¤ì •
		FButtonStyle ButtonStyle;
		ButtonStyle.Normal.TintColor = FSlateColor(FLinearColor::Gray);
		ButtonStyle.Hovered.TintColor = FSlateColor(FLinearColor(0.7f, 0.7f, 1.f, 1.f));
		ButtonStyle.Pressed.TintColor = FSlateColor(FLinearColor(0.5f, 0.5f, 1.f, 1.f));
		Button->SetStyle(ButtonStyle);
	}
	MaterialTypeChangePanel->SetVisibility(ESlateVisibility::Hidden);
}

void UMaterialGeneratePanel::OnTireBtnClicked()
{
	MaterialTypeText->SetText(FText::FromString(MatEnumPtr->GetNameStringByIndex(0)));
	matTypeSelected = EMaterialType::Tire;
	MaterialTypeChangePanel->SetVisibility(ESlateVisibility::Hidden);

}

void UMaterialGeneratePanel::OnFoliageBtnClicked()
{
	MaterialTypeText->SetText(FText::FromString(MatEnumPtr->GetNameStringByIndex(1)));
	matTypeSelected = EMaterialType::Foliage;
	MaterialTypeChangePanel->SetVisibility(ESlateVisibility::Hidden);

}

void UMaterialGeneratePanel::OnVideoBtnClicked()
{
	MaterialTypeText->SetText(FText::FromString(MatEnumPtr->GetNameStringByIndex(2)));
	matTypeSelected = EMaterialType::Video;
	MaterialTypeChangePanel->SetVisibility(ESlateVisibility::Hidden);

}

void UMaterialGeneratePanel::OnSubsurfaceBtnClicked()
{
	MaterialTypeText->SetText(FText::FromString(MatEnumPtr->GetNameStringByIndex(3)));
	matTypeSelected = EMaterialType::Subsurface;
	MaterialTypeChangePanel->SetVisibility(ESlateVisibility::Hidden);

}

void UMaterialGeneratePanel::OnCarPaintBtnClicked()
{
	MaterialTypeText->SetText(FText::FromString(MatEnumPtr->GetNameStringByIndex(4)));
	matTypeSelected = EMaterialType::CarPaint;
	MaterialTypeChangePanel->SetVisibility(ESlateVisibility::Hidden);

}

void UMaterialGeneratePanel::OnWaterBtnClicked()
{
	MaterialTypeText->SetText(FText::FromString(MatEnumPtr->GetNameStringByIndex(5)));
	matTypeSelected = EMaterialType::Water;
	MaterialTypeChangePanel->SetVisibility(ESlateVisibility::Hidden);

}

void UMaterialGeneratePanel::OnEmissiveBtnClicked()
{
	MaterialTypeText->SetText(FText::FromString(MatEnumPtr->GetNameStringByIndex(6)));
	matTypeSelected = EMaterialType::Emissive;
	MaterialTypeChangePanel->SetVisibility(ESlateVisibility::Hidden);

}

void UMaterialGeneratePanel::OnFabricBtnClicked()
{
	MaterialTypeText->SetText(FText::FromString(MatEnumPtr->GetNameStringByIndex(7)));
	matTypeSelected = EMaterialType::Fabric;
	MaterialTypeChangePanel->SetVisibility(ESlateVisibility::Hidden);

}

void UMaterialGeneratePanel::OnGlassBtnClicked()
{
	MaterialTypeText->SetText(FText::FromString(MatEnumPtr->GetNameStringByIndex(8)));
	matTypeSelected = EMaterialType::Glass;
	MaterialTypeChangePanel->SetVisibility(ESlateVisibility::Hidden);

}

void UMaterialGeneratePanel::OnStandardBtnClicked()
{
	MaterialTypeText->SetText(FText::FromString(MatEnumPtr->GetNameStringByIndex(9)));
	matTypeSelected = EMaterialType::Standard;
	MaterialTypeChangePanel->SetVisibility(ESlateVisibility::Hidden);

}

void UMaterialGeneratePanel::OnCreateMaterialBtnClicked()
{
	
	// ë°ì´í„° ìƒì„±
	UMaterialThumbnailData* NewItem = NewObject<UMaterialThumbnailData>(this);
	const UEnum* MaterialEnum = StaticEnum<EMaterialType>();
	FText EnumDisplayNameText = MaterialEnum->GetDisplayNameTextByValue(
		static_cast<int64>(matTypeSelected)
	);
	FString EnumNameString = EnumDisplayNameText.ToString();
	FString NewMaterialName = FString::Printf(TEXT("New %s"), *EnumNameString);
	
	NewItem->MaterialName = NewMaterialName;
	NewItem->MaterialType = matTypeSelected;

	UE_LOG(LogTemp, Warning, TEXT("NewItem MaterialName: %s"), *NewItem->MaterialName);
	UE_LOG(LogTemp, Warning, TEXT("NewItem MaterialType: %d"), static_cast<int32>(NewItem->MaterialType));


	// ìƒ˜í”Œ ì¸ë„¤ì¼ (ì„ì‹œë¡œ Content í´ë”ì—ì„œ ë¶ˆëŸ¬ì˜¤ê¸°)
	NewItem->Thumbnail = LoadObject<UTexture2D>(nullptr, TEXT("/Game/UI/Thumbnails/T_GlassIcon.T_GlassIcon"));

	// TileViewì— ì¶”ê°€
	MaterialTileView->AddItem(NewItem);
}

