// Fill out your copyright notice in the Description page of Project Settings.


#include "UI/MainOverlay.h"

#include "SocketSubsystem.h"
#include "Components/VerticalBox.h"
#include "Components/Button.h"
#include "Components/CanvasPanel.h"
#include "Components/EditableTextBox.h"
#include "Components/WidgetSwitcher.h"
#include "Kismet/GameplayStatics.h"


void UMainOverlay::NativeConstruct()
{
	Super::NativeConstruct();

}

void UMainOverlay::NativeOnInitialized()
{
	Super::NativeOnInitialized();

	if (HostBtn)
	{
		HostBtn->OnClicked.AddDynamic(this, &UMainOverlay::CreateHost);
	}

	if (JoinBtn)
	{
		JoinBtn->OnClicked.AddDynamic(this, &UMainOverlay::GoToJoinPage);
	}

	if (CancelBtn)
	{
		CancelBtn->OnClicked.AddDynamic(this, &UMainOverlay::GoToFirstPage);
	}

	if (JoinConfirmBtn)
	{
		JoinConfirmBtn->OnClicked.AddDynamic(this, &UMainOverlay::OnJoinConfirmClicked);
	}
	
	// ë„¤íŠ¸ì›Œí¬ ì‹¤íŒ¨ ë¸ë¦¬ê²Œì´íŠ¸ ë°”ì¸ë”©
	if (GetWorld() && GetWorld()->GetFirstPlayerController())
	{
		GEngine->OnNetworkFailure().AddUObject(this, &UMainOverlay::HandleNetworkFailure);
	}

	// ğŸ”¹ ë§ˆìš°ìŠ¤ ì»¤ì„œ í™œì„±í™”
	if (APlayerController* PC = GetWorld()->GetFirstPlayerController())
	{
		PC->bShowMouseCursor = true;
		PC->SetInputMode(FInputModeUIOnly());
		PC->SetIgnoreLookInput(true);  // (ì„ íƒ) ë§ˆìš°ìŠ¤ ì›€ì§ì—¬ë„ ì¹´ë©”ë¼ ì•ˆì›€ì§ì´ê²Œ
		PC->SetIgnoreMoveInput(true);  // (ì„ íƒ) WASD ë“± ë§‰ê¸°
		PC->SetInputMode(FInputModeUIOnly());
	}
}




//Hostë²„íŠ¼ ëˆŒë ¸ì„ ë•Œ

void UMainOverlay::CreateHost()
{
	UE_LOG(LogTemp, Warning, TEXT("UMainOverlay::CreateHost() - Host Button Clicked!")); // Diagnostic log

	bool bCanBindAll;
	TSharedPtr<FInternetAddr> LocalAddr = ISocketSubsystem::Get(PLATFORM_SOCKETSUBSYSTEM)->GetLocalHostAddr(*GLog, bCanBindAll);
    
	url = LocalAddr.IsValid() ? LocalAddr->ToString(false) : "127.0.0.1";
	
	UE_LOG(LogTemp, Display, TEXT("Host URL : %s"), *url);

	// âœ… Viewportì—ì„œ ì œê±°
	RemoveFromParent();
	
	UGameplayStatics::OpenLevel(this, FName("MainMap"), true, "listen");


}



//Cancelë²„íŠ¼ ëˆŒë ¸ì„ ë•Œ
void UMainOverlay::GoToFirstPage()
{
	if (WidgetSwitcher)
	{
		WidgetSwitcher->SetActiveWidgetIndex(0);
	}
}

//Joinë²„íŠ¼ ëˆŒë ¸ì„ ë•Œ
void UMainOverlay::GoToJoinPage()
{
	if (WidgetSwitcher)
	{
		WidgetSwitcher->SetActiveWidgetIndex(1);
	}
}

//Joiní˜ì´ì§€ì˜ Confirmë²„íŠ¼ ëˆŒë ¸ì„ë•Œ
void UMainOverlay::OnJoinConfirmClicked()
{
	if (!UrlInputBox)  return;

	FText Text = UrlInputBox->GetText();
	url = Text.ToString();

	// URL/IP ê²€ì¦ (ê°„ë‹¨ ì˜ˆì‹œ)
	if (url.IsEmpty())
	{
		UE_LOG(LogTemp, Warning, TEXT("IP/URLì´ ë¹„ì–´ìˆìŒ"))
		return;
	}

	//RemoveFromParent();

	//ì„œë²„ë¡œ ì´ë™
	UGameplayStatics::OpenLevel(this, *url, true);
}

void UMainOverlay::HandleNetworkFailure(UWorld* World, UNetDriver* NetDriver, ENetworkFailure::Type FailureType,
	const FString& ErrorString)
{
	// ì„œë²„ ì ‘ì† ì‹¤íŒ¨ ì‹œ ë©”ì‹œì§€ ì¶œë ¥
	UE_LOG(LogTemp, Error, TEXT("ë„¤íŠ¸ì›Œí¬ ì‹¤íŒ¨: %s"), *ErrorString);

	// UIì— íŒì—… ë©”ì‹œì§€ ë„ìš°ê¸° ê°€ëŠ¥
	// ì˜ˆ: UWidgetBlueprintLibrary::Create(UserWidget, ...) + AddToViewport()
}
